export const industries = [
  "Construction",
  "Manufacturing",
  "IT & SaaS",
  "Healthcare",
  "Facilities Management",
  "Logistics",
  "Engineering",
  "Public Sector",
];

export const leadStatuses = [
  "New",
  "Enriched",
  "Contacted",
  "Follow-Up",
  "Interested",
  "Discovery Call Booked",
  "Proposal Sent",
  "Won",
  "Lost",
];

export const mockLeads = [
  {
    id: "1",
    companyName: "BuildCorp Solutions",
    website: "https://buildcorp.example.com",
    industry: "Construction",
    location: "London",
    country: "United Kingdom",
    size: "50-100",
    score: 95,
    status: "Interested",
    isoNeeds: ["ISO 9001", "ISO 14001"],
    contactName: "James Wilson",
    contactEmail: "j.wilson@buildcorp.example.com",
    signals: ["Tender Requirement", "Hiring HSE Manager"],
  },
  {
    id: "2",
    companyName: "TechFlow Systems",
    website: "https://techflow.example.com",
    industry: "IT & SaaS",
    location: "Manchester",
    country: "United Kingdom",
    size: "10-50",
    score: 82,
    status: "New",
    isoNeeds: ["ISO 27001"],
    contactName: "Sarah Chen",
    contactEmail: "sarah@techflow.example.com",
    signals: ["Hiring Quality Manager"],
  },
  {
    id: "3",
    companyName: "EcoLogistics Ltd",
    website: "https://ecologistics.example.com",
    industry: "Logistics",
    location: "Birmingham",
    country: "United Kingdom",
    size: "100-250",
    score: 88,
    status: "Discovery Call Booked",
    isoNeeds: ["ISO 14001", "ISO 50001"],
    contactName: "Robert Taylor",
    contactEmail: "r.taylor@ecologistics.example.com",
    signals: ["Public Sector Bid"],
  },
  {
    id: "4",
    companyName: "SecureNet IT",
    website: "https://securenet.example.com",
    industry: "IT & SaaS",
    location: "New York",
    country: "USA",
    size: "25-50",
    score: 91,
    status: "Proposal Sent",
    isoNeeds: ["ISO 27001", "ISO 22301"],
    contactName: "Emily Davis",
    contactEmail: "e.davis@securenet.example.com",
    signals: ["Cybersecurity growth"],
  },
  {
    id: "5",
    companyName: "MedSupply Hub",
    website: "https://medsupply.example.com",
    industry: "Healthcare",
    location: "Berlin",
    country: "Germany",
    size: "150-300",
    score: 75,
    status: "Enriched",
    isoNeeds: ["ISO 13485", "ISO 9001"],
    contactName: "Michael Ross",
    contactEmail: "m.ross@medsupply.example.com",
    signals: ["Supplier compliance requirement"],
  },
];

export const mockAnalytics = {
  kpis: {
    leadsFound: 1284,
    leadsEnriched: 942,
    hotLeads: 84,
    emailsSent: 452,
    openRate: 64.5,
    replyRate: 12.8,
    callsBooked: 12,
    proposalsSent: 8,
    revenueForecast: 45000,
  },
  leadGrowth: [
    { date: "2026-05-01", leads: 400 },
    { date: "2026-05-05", leads: 600 },
    { date: "2026-05-10", leads: 850 },
    { date: "2026-05-15", leads: 1284 },
  ],
  campaignStats: [
    { name: "ISO 9001 Intro", sent: 150, opened: 95, replied: 18 },
    { name: "Tender Support", sent: 120, opened: 82, replied: 24 },
    { name: "Cybersecurity", sent: 100, opened: 68, replied: 12 },
    { name: "Eco-Compliance", sent: 82, opened: 47, replied: 6 },
  ],
};
